### ISSUE TITLE
mythbackend Crash when editing recording rule

### ISSUE THREAD

**Issue by pmhahn** [MythTV/mythtv#494]
* **Platform**:
Debian 11.2 Bullseye

* **MythTV version**:
31.0+fixes.20210506.b2ed400037-0ubuntu0

* **Package version**:
From git b2ed400037  (2021-05-06)

* **Component**:
mythtv-backennd

### What steps will reproduce the bug?
* Create a recording from Web-frontend
* Edit recording rule
** Changesome `Post processiong` settings
** Click `Save changes`

### How often does it reproduce? Is there a required condition?
Every time

### What is the expected behaviour?
Should not crash

### What do you see instead?
`mythtv-backend` crashed and writes a `core` file

### Additional information
Maybe see #446

https://github.com/MythTV/mythtv/blob/fixes/31/mythtv/libs/libmythupnp/serverSideScripting.cpp#L220

##### gdb
```
# gdb --silent --batch -ex 'bt -full' /usr/bin/mythbackend core.2519 
…
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/mythbackend --logpath /var/log/mythtv/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::__atomic_base<int>::load (__m=std::memory_order_relaxed, this=0x255) at /usr/include/c++/10/bits/atomic_base.h:420
420           load(memory_order __m = memory_order_seq_cst) const noexcept
[Current thread is 1 (Thread 0x7fb70affd700 (LWP 14900))]
#0  std::__atomic_base<int>::load (__m=std::memory_order_relaxed, this=0x255) at /usr/include/c++/10/bits/atomic_base.h:420
        __b = <optimized out>
#1  QAtomicOps<int>::loadRelaxed<int> (_q_value=...) at ../../include/QtCore/../../src/corelib/thread/qatomic_cxx11.h:239
No locals.
#2  QBasicAtomicInteger<int>::loadRelaxed (this=0x255) at ../../include/QtCore/../../src/corelib/thread/qbasicatomic.h:107
No locals.
#3  QtPrivate::RefCount::ref (this=0x255) at ../../include/QtCore/../../src/corelib/tools/qrefcount.h:55
        count = <optimized out>
        count = <optimized out>
#4  QString::QString (other=..., this=0x7fb70affbd50) at ../../include/QtCore/../../src/corelib/text/qstring.h:1094
No locals.
#5  v_construct_helper<QString> (t=..., x=0x7fb70affbd50) at ../../include/QtCore/5.15.2/QtCore/private/../../../../../src/corelib/kernel/qvariant_p.h:128
No locals.
#6  v_construct<QString> (t=..., x=0x7fb70affbd50) at ../../include/QtCore/5.15.2/QtCore/private/../../../../../src/corelib/kernel/qvariant_p.h:157
No locals.
#7  QVariant::QVariant (this=0x7fb70affbd50, val=...) at kernel/qvariant.cpp:2179
No locals.
#8  0x00007fb7ddc0fe44 in ServerSideScripting::EvaluatePage (this=0x558b45f512b8, pOutStream=0x7fb70affc3e0, sFileName=..., pRequest=0x7fb704041fe0, cspToken=...) at serverSideScripting.cpp:220
        key = @0x7fb704048740: {static null = {<No data fields>}, d = 0x7fb70405a3d0}
        value = {d = {data = {c = 85 'U', uc = 85 'U', s = 597, sc = 85 'U', us = 597, i = 597, u = 597, l = 597, ul = 597, b = 85, d = 2.9495719056722419e-321, f = 8.36575183e-43, real = 2.9495719056722419e-321, ll = 597, ull = 597, o = 0x255, ptr = 0x255, shared = 0x255}, type = 10, is_shared = 0, is_null = 0}}
        it = {i = 0x7fb704048728}
        pInfo = 0x7fb70401dca0
        serverVars = {d = 0x0}
        clientIP = {d = {d = 0x0}}
        session = {m_userId = 0, m_name = {static null = {<No data fields>}, d = 0x0}, m_sessionToken = {static null = {<No data fields>}, d = 0x0}, m_sessionCreated = {d = {d = 0x0, data = {status = 0, msecs = 0}}}, m_sessionLastActive = {d = {d = 0x0, data = {status = 0, msecs = 0}}}, m_sessionExpires = {d = {d = 0x0, data = {status = 0, msecs = 0}}}, m_sessionClient = {static null = {<No data fields>}, d = 0x0}, m_permissionsList = {d = 0x0}}
        outStream = {<QObject> = {_vptr.QObject = 0x0, static staticMetaObject = {d = {superdata = {direct = 0x0}, stringdata = 0x7fb7dc813b20 <qt_meta_stringdata_QObject>, data = 0x7fb7dc813a00 <qt_meta_data_QObject>, static_metacall = 0x7fb7dc67ed30 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x0}, static staticQtMetaObject = {d = {superdata = {direct = 0x0}, stringdata = 0x7fb7dc816ac0 <qt_meta_stringdata_Qt>, data = 0x7fb7dc813c40 <qt_meta_data_Qt>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, <QScriptable> = {d_ptr = {d = 0x0}}, static staticMetaObject = {d = {superdata = 0x7fb7dc8d7100 <QObject::staticMetaObject>, stringdata = 0x7fb7ddc546e0 <qt_meta_stringdata_OutputStream>, data = 0x7fb7ddc54780 <qt_meta_data_OutputStream>, static_metacall = 0x7fb7ddc443c0 <OutputStream::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, m_pTextStream = 0x0}
        fileInfo = {d_ptr = {d = 0x7fb70405b470}}
        params = {d = 0x7fb70404bdf0}
        mapCookies = {d = 0x0}
        sessionVars = {d = 0x0}
        respHeaderMap = {d = 0x0}
        qsCspToken = {d_ptr = {d = 0x0}}
        requestHeaders = {d = 0x0}
        serverIP = {d = {d = 0x0}}
        array = {d = 0x7fb7dc7314a0 <QMapDataBase::shared_null>}
        ret = {d_ptr = {d = 0x0}}
        dtLastModified = {d = {d = 0x16c5e8c45f88f, data = {status = 143, msecs = 1564954347000}}}
        mapParams = {d = 0x7fb70404be20}
        validChars = {priv = 0x7fb704030220}
        prevArrayName = {static null = {<No data fields>}, d = 0x7fb7c4014960}
        mapHeaders = {d = 0x0}
        requestCookies = {d = 0x0}
        args = {<QListSpecialMethods<QScriptValue>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x0}, d = 0x0}}
        __FUNCTION__ = "EvaluatePage"
        responseHeaders = {d = 0x0}
        it = {i = 0x0}
#9  0x00007fb7ddc0d7e3 in HtmlServerExtension::ProcessRequest (this=0x558b45f51290, pRequest=0x7fb704041fe0) at htmlserver.cpp:206
        stream = {_vptr.QTextStream = 0x7fb7dc8e0a28 <vtable for QTextStream+16>, d_ptr = {d = 0x7fb70405b870}}
        cspNonce = {d = 0x7fb7040670e0}
        sSuffix = {static null = {<No data fields>}, d = 0x7fb704048ad0}
        sMimeType = {static null = {<No data fields>}, d = 0x7fb7b803c720}
        cspPolicy = {static null = {<No data fields>}, d = 0x7fb70404cb70}
        sResName = {static null = {<No data fields>}, d = 0x7fb70405b3e0}
        bStorageGroupFile = false
        oInfo = {d_ptr = {d = 0x7fb70404afc0}}
#10 0x00007fb7ddbd04d7 in HttpServer::DelegateRequest (this=0x558b45f716c0, pRequest=0x7fb704041fe0) at httpserver.cpp:402
        bProcessed = false
        __FUNCTION__ = "DelegateRequest"
        list = {<QListSpecialMethods<HttpServerExtension*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fb7dc731470 <QListData::shared_null>}, d = 0x7fb7dc731470 <QListData::shared_null>}}
        it = {i = 0x558b46048818}
#11 0x00007fb7ddbd1546 in HttpWorker::run (this=0x558b45f7cfc0) at httpserver.cpp:579
        nTimeout = 10
        nBytes = 2983
        bTimeout = false
        bKeepAlive = true
        pRequest = 0x7fb704041fe0
        pSocket = 0x7fb704057710
        bEncrypted = false
        __FUNCTION__ = "run"
        nRequestsHandled = 0
        writeTimeout = 184535408
#12 0x00007fb7dd9937cb in MPoolThread::run (this=0x558b4607add0) at mthreadpool.cpp:140
        autodelete = true
        t = {m_timer = {t1 = 6610, t2 = 203902777}, m_offset = 0}
        locker = {val = 94056663723505}
#13 0x00007fb7dd99012c in MThreadInternal::run (this=0x558b4606c1e0) at mthread.cpp:79
No locals.
#14 0x00007fb7dc468be1 in QThreadPrivate::start (arg=0x558b4606c1e0) at thread/qthread_unix.cpp:329
        thr = 0x558b4606c1e0
        data = 0x7fb70affca38
        __clframe = {__cancel_routine = 0x7fb7dc4682b0 <QThreadPrivate::finish(void*)>, __cancel_arg = 0x558b4606c1e0, __do_it = 1, __cancel_type = <optimized out>}
#15 0x00007fb7dc382ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140424140281600, 4475805405130864911, 140724542761230, 140724542761231, 140424140278592, 8396800, -4507165675137451761, -4507266236588803825}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#16 0x00007fb7dc0cbdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb) frame 8
(gdb) print *it.i
$3 = {<QMapNodeBase> = {p = 0, left = 0x7fb704042520, right = 0x0}, key = {static null = {<No data fields>}, d = 0x7fb70405a3d0}, value = {static null = {<No data fields>}, d = 0x255}}
```

##### HAR
```
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "_initiator": {
          "type": "script",
          "stack": {
            "callFrames": [
              {
                "functionName": "send",
                "scriptId": "76",
                "url": "http://barrel.fritz.box:6544/3rdParty/jquery/jquery-2.1.4.min.js",
                "lineNumber": 3,
                "columnNumber": 14952
              },
              {
                "functionName": "ajax",
                "scriptId": "76",
                "url": "http://barrel.fritz.box:6544/3rdParty/jquery/jquery-2.1.4.min.js",
                "lineNumber": 3,
                "columnNumber": 10711
              },
              {
                "functionName": "saveFormData",
                "scriptId": "79",
                "url": "http://barrel.fritz.box:6544/tv/js/common.js",
                "lineNumber": 647,
                "columnNumber": 6
              },
              {
                "functionName": "saveRecordingSchedule",
                "scriptId": "77",
                "url": "http://barrel.fritz.box:6544/tv/js/schedule.js",
                "lineNumber": 4,
                "columnNumber": 8
              },
              {
                "functionName": "onclick",
                "scriptId": "95",
                "url": "http://barrel.fritz.box:6544/tv/schedule.qsp?ChanId=2001&amp;StartTime=2022-02-20T20:45:00.000Z",
                "lineNumber": 541,
                "columnNumber": 91
              }
            ]
          }
        },
        "_priority": "High",
        "_resourceType": "xhr",
        "cache": {},
        "request": {
          "method": "POST",
          "url": "http://barrel.fritz.box:6544/tv/ajax_backends/dvr_util.qsp",
          "httpVersion": "",
          "headers": [
            {
              "name": "Host",
              "value": "barrel.fritz.box:6544"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "2179"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Accept",
              "value": "text/plain, */*; q=0.01"
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Mobile Safari/537.36"
            },
            {
              "name": "Content-Type",
              "value": "application/x-www-form-urlencoded; charset=UTF-8"
            },
            {
              "name": "Origin",
              "value": "http://barrel.fritz.box:6544"
            },
            {
              "name": "Referer",
              "value": "http://barrel.fritz.box:6544/tv/schedule.qsp?ChanId=2001&amp;StartTime=2022-02-20T20:45:00.000Z"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Accept-Language",
              "value": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7"
            },
            {
              "name": "Cookie",
              "value": "_ga=GA1.2.405253519.1586602431; _ga_4SMHY28C24=GS1.1.1616251842.2.0.1616251842.0; mythweb_id=5fmiauecu52q2255dd078dq209"
            }
          ],
          "queryString": [],
          "cookies": [
            {
              "name": "_ga",
              "value": "GA1.2.405253519.1586602431",
              "path": "/",
              "domain": ".fritz.box",
              "expires": "2023-03-20T11:48:34.000Z",
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "_ga_4SMHY28C24",
              "value": "GS1.1.1616251842.2.0.1616251842.0",
              "path": "/",
              "domain": ".fritz.box",
              "expires": "2023-03-20T14:50:42.000Z",
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "mythweb_id",
              "value": "5fmiauecu52q2255dd078dq209",
              "path": "/",
              "domain": "barrel.fritz.box",
              "expires": "2022-03-22T18:25:02.269Z",
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": -1,
          "bodySize": 2179,
          "postData": {
            "mimeType": "application/x-www-form-urlencoded; charset=UTF-8",
            "text": "_action=saveRecordingRule&Id=1079&Title=R%C3%BCbezahls+Schatz&SubTitle=14&Description=W%C3%A4hrend+die+Baronin+nicht+nur+plant%2C+Raubbau+an+den+W%C3%A4ldern+zu+begehen%2C+sondern+auch+R%C3%BCbezahls+Sch%C3%A4tze+zu+stehlen%2C+treibt+den+schalkhaften+und+gestaltwandlerischen+Berggeist+zuallererst+die+Frage+um%2C+ob+sich+seine+Liebe+zu+einer+Sterblichen+erf%C3%BCllen+k%C3%B6nnte.+Die+Baronin+von+Harrant+ist+zwar+pleite%2C+hat+aber+%C3%A4u%C3%9Ferst+ehrgeizige+Pl%C3%A4ne.+Mit+geliehenem+Geld+m%C3%B6chte+sie+ein+S%C3%A4gewerk+im+Riesengebirge+errichten%2C+vor+allem+aber+soll+der+sagenhafte+Schatz+des+R%C3%BCbezahl+so+schnell+wie+m%C3%B6glich+ihre+leeren+Kassen+f%C3%BCllen.+Um+herauszufinden%2C+wie+sie+an+das+Gold+des+Berggeistes+kommt%2C+erpresst+sie+ihre+Magd+Rosa+-+jene+sch%C3%B6ne%2C+junge+Frau%2C+auf+die+der+J%C3%A4ger+Montanus+ein+Auge+geworfen+hat.+Montanus+aber+ist+nichts+als+eine+der+vielen+Gestalten%2C+unter+denen+sich+der+Sch%C3%BCtzer+der+Berge+unter+die+Menschen+mischt.+Je+n%C3%A4her+sich+Rosa+und+er+kommen%2C+desto+mehr+nimmt+die+perfide+Intrige+der+Harrantin+Gestalt+an.+Als+sie+erf%C3%A4hrt%2C+dass+es+der+magischen+Springwurz+bedarf%2C+um+in+R%C3%BCbezahls+Schatzkammer+zu+gelangen%2C+und+deutlich+wird%2C+dass+sich+R%C3%BCbezahl+mehr+in+seine+Liebesdinge+verstrickt%2C+als+es+seiner+Aufgabe+als+W%C3%A4chter+%C3%BCber+Land+und+Leute+gutt%C3%A4te%2C+scheint+das+Ungl%C3%BCck+unaufhaltsam.&Category=Fantasy&StartTime=2022-02-20T20%3A45%3A00.000Z&EndTime=2022-02-20T22%3A15%3A00.000Z&SeriesId=146852202&ProgramId=&ChanId=2001&CallSign=3sat+HD&Type=Single+Record&RecPriority=-1&StartOffset=0&EndOffset=0&DupMethod=Subtitle+then+Description&DupIn=All+Recordings&PreferredInput=0&Inactive=0&Filter%5B_0%5D=0&Filter%5B_1%5D=0&Filter%5B_2%5D=0&Filter%5B_3%5D=0&Filter%5B_4%5D=0&Filter%5B_5%5D=0&Filter%5B_6%5D=0&Filter%5B_7%5D=0&Filter%5B_8%5D=0&Filter%5B_9%5D=0&Filter%5B_10%5D=0&Filter%5B_11%5D=0&Filter%5B_12%5D=0&RecGroup=Tine&StorageGroup=Default&PlayGroup=Default&MaxEpisodes=0&MaxNewest=1&AutoExpire=1&AutoMetaLookup=1&AutoCommflag=1&AutoTranscode=0&Transcoder=0&AutoUserJob1=0&AutoUserJob2=0&AutoUserJob3=0&AutoUserJob4=0&Inetref=&Season=0&Episode=0",
            "params": [
              {
                "name": "_action",
                "value": "saveRecordingRule"
              },
              {
                "name": "Id",
                "value": "1079"
              },
              {
                "name": "Title",
                "value": "R%C3%BCbezahls+Schatz"
              },
              {
                "name": "SubTitle",
                "value": "14"
              },
              {
                "name": "Description",
                "value": "W%C3%A4hrend+die+Baronin+nicht+nur+plant%2C+Raubbau+an+den+W%C3%A4ldern+zu+begehen%2C+sondern+auch+R%C3%BCbezahls+Sch%C3%A4tze+zu+stehlen%2C+treibt+den+schalkhaften+und+gestaltwandlerischen+Berggeist+zuallererst+die+Frage+um%2C+ob+sich+seine+Liebe+zu+einer+Sterblichen+erf%C3%BCllen+k%C3%B6nnte.+Die+Baronin+von+Harrant+ist+zwar+pleite%2C+hat+aber+%C3%A4u%C3%9Ferst+ehrgeizige+Pl%C3%A4ne.+Mit+geliehenem+Geld+m%C3%B6chte+sie+ein+S%C3%A4gewerk+im+Riesengebirge+errichten%2C+vor+allem+aber+soll+der+sagenhafte+Schatz+des+R%C3%BCbezahl+so+schnell+wie+m%C3%B6glich+ihre+leeren+Kassen+f%C3%BCllen.+Um+herauszufinden%2C+wie+sie+an+das+Gold+des+Berggeistes+kommt%2C+erpresst+sie+ihre+Magd+Rosa+-+jene+sch%C3%B6ne%2C+junge+Frau%2C+auf+die+der+J%C3%A4ger+Montanus+ein+Auge+geworfen+hat.+Montanus+aber+ist+nichts+als+eine+der+vielen+Gestalten%2C+unter+denen+sich+der+Sch%C3%BCtzer+der+Berge+unter+die+Menschen+mischt.+Je+n%C3%A4her+sich+Rosa+und+er+kommen%2C+desto+mehr+nimmt+die+perfide+Intrige+der+Harrantin+Gestalt+an.+Als+sie+erf%C3%A4hrt%2C+dass+es+der+magischen+Springwurz+bedarf%2C+um+in+R%C3%BCbezahls+Schatzkammer+zu+gelangen%2C+und+deutlich+wird%2C+dass+sich+R%C3%BCbezahl+mehr+in+seine+Liebesdinge+verstrickt%2C+als+es+seiner+Aufgabe+als+W%C3%A4chter+%C3%BCber+Land+und+Leute+gutt%C3%A4te%2C+scheint+das+Ungl%C3%BCck+unaufhaltsam."
              },
              {
                "name": "Category",
                "value": "Fantasy"
              },
              {
                "name": "StartTime",
                "value": "2022-02-20T20%3A45%3A00.000Z"
              },
              {
                "name": "EndTime",
                "value": "2022-02-20T22%3A15%3A00.000Z"
              },
              {
                "name": "SeriesId",
                "value": "146852202"
              },
              {
                "name": "ProgramId",
                "value": ""
              },
              {
                "name": "ChanId",
                "value": "2001"
              },
              {
                "name": "CallSign",
                "value": "3sat+HD"
              },
              {
                "name": "Type",
                "value": "Single+Record"
              },
              {
                "name": "RecPriority",
                "value": "-1"
              },
              {
                "name": "StartOffset",
                "value": "0"
              },
              {
                "name": "EndOffset",
                "value": "0"
              },
              {
                "name": "DupMethod",
                "value": "Subtitle+then+Description"
              },
              {
                "name": "DupIn",
                "value": "All+Recordings"
              },
              {
                "name": "PreferredInput",
                "value": "0"
              },
              {
                "name": "Inactive",
                "value": "0"
              },
              {
                "name": "Filter%5B_0%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_1%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_2%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_3%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_4%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_5%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_6%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_7%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_8%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_9%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_10%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_11%5D",
                "value": "0"
              },
              {
                "name": "Filter%5B_12%5D",
                "value": "0"
              },
              {
                "name": "RecGroup",
                "value": "Tine"
              },
              {
                "name": "StorageGroup",
                "value": "Default"
              },
              {
                "name": "PlayGroup",
                "value": "Default"
              },
              {
                "name": "MaxEpisodes",
                "value": "0"
              },
              {
                "name": "MaxNewest",
                "value": "1"
              },
              {
                "name": "AutoExpire",
                "value": "1"
              },
              {
                "name": "AutoMetaLookup",
                "value": "1"
              },
              {
                "name": "AutoCommflag",
                "value": "1"
              },
              {
                "name": "AutoTranscode",
                "value": "0"
              },
              {
                "name": "Transcoder",
                "value": "0"
              },
              {
                "name": "AutoUserJob1",
                "value": "0"
              },
              {
                "name": "AutoUserJob2",
                "value": "0"
              },
              {
                "name": "AutoUserJob3",
                "value": "0"
              },
              {
                "name": "AutoUserJob4",
                "value": "0"
              },
              {
                "name": "Inetref",
                "value": ""
              },
              {
                "name": "Season",
                "value": "0"
              },
              {
                "name": "Episode",
                "value": "0"
              }
            ]
          }
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_EMPTY_RESPONSE"
        },
        "serverIPAddress": "",
        "startedDateTime": "2022-02-20T18:40:11.079Z",
        "time": 1382.054999936372,
        "timings": {
          "blocked": 1382.054999936372,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": 2.6630000211298466
        }
      },
      {
        "_initiator": {
          "type": "script",
          "stack": {
            "callFrames": [
              {
                "functionName": "WebSocketEventHandler.Open",
                "scriptId": "9",
                "url": "http://barrel.fritz.box:6544/js/websocket_events.js",
                "lineNumber": 154,
                "columnNumber": 21
              },
              {
                "functionName": "WebSocketEventHandler.Reconnect",
                "scriptId": "9",
                "url": "http://barrel.fritz.box:6544/js/websocket_events.js",
                "lineNumber": 179,
                "columnNumber": 9
              },
              {
                "functionName": "",
                "scriptId": "9",
                "url": "http://barrel.fritz.box:6544/js/websocket_events.js",
                "lineNumber": 103,
                "columnNumber": 71
              }
            ],
            "parent": {
              "description": "setInterval",
              "callFrames": [
                {
                  "functionName": "WebSocketEventHandler.OnClose",
                  "scriptId": "9",
                  "url": "http://barrel.fritz.box:6544/js/websocket_events.js",
                  "lineNumber": 103,
                  "columnNumber": 39
                },
                {
                  "functionName": "websocket.onclose",
                  "scriptId": "9",
                  "url": "http://barrel.fritz.box:6544/js/websocket_events.js",
                  "lineNumber": 156,
                  "columnNumber": 55
                }
              ]
            }
          }
        },
        "_priority": null,
        "_resourceType": "websocket",
        "_webSocketMessages": [
          {
            "type": "send",
            "time": 1645382424.6335492,
            "opcode": 1,
            "data": "WS_EVENT_ENABLE"
          },
          {
            "type": "send",
            "time": 1645382424.6341002,
            "opcode": 1,
            "data": "WS_EVENT_SET_FILTER "
          }
        ],
        "cache": {},
        "request": {
          "method": "GET",
          "url": "ws://barrel.fritz.box:6549/",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Origin",
              "value": "http://barrel.fritz.box:6544"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Host",
              "value": "barrel.fritz.box:6549"
            },
            {
              "name": "Accept-Language",
              "value": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7"
            },
            {
              "name": "Sec-WebSocket-Key",
              "value": "AjpCAwNb3QA8dM94pfRPnA=="
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Mobile Safari/537.36"
            },
            {
              "name": "Upgrade",
              "value": "websocket"
            },
            {
              "name": "Sec-WebSocket-Extensions",
              "value": "permessage-deflate; client_max_window_bits"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Connection",
              "value": "Upgrade"
            },
            {
              "name": "Sec-WebSocket-Version",
              "value": "13"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 571,
          "bodySize": 0
        },
        "response": {
          "status": 101,
          "statusText": "Switching Protocols",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Connection",
              "value": "Upgrade"
            },
            {
              "name": "Sec-WebSocket-Accept",
              "value": "x50xvN2+83yD+knqLq/vVGBt1uY="
            },
            {
              "name": "Upgrade",
              "value": "websocket"
            }
          ],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown",
            "compression": 129
          },
          "redirectURL": "",
          "headersSize": 129,
          "bodySize": -129,
          "_transferSize": 0,
          "_error": null
        },
        "serverIPAddress": "",
        "startedDateTime": "2022-02-20T18:40:22.482Z",
        "time": 2151.203000219539,
        "timings": {
          "blocked": -1,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 2151.203000219539,
          "receive": 0,
          "_blocked_queueing": -1
        }
      }
    ]
  }
}
```

**Comment by rcrdnalor** [comment]
@pmhahn : The Web Application (https://www.mythtv.org/wiki/Web_Application) replaced the Web-Frontend in MythTV v34 and Mythtv / master.
Is this issue still valid on recent installations ?
