### ISSUE TITLE
TV grabber ttvdb.py fails at tvdb_api:auth

### ISSUE THREAD

**Issue by hamelg** [MythTV/mythtv#498]
* **Platform**: Archlinux

* **MythTV version**: up to date fixes/31

* **Component**: ttvdb.py
python 3.10.2-1
python-requests-cache 0.9.3-1
python-requests 2.27.1-1
python-urllib3 1.26.8-1

### What steps will reproduce the bug?
run ttvdb.py anything.

```
$ ./ttvdb.py Chernobyl
DEBUG:requests_cache.backends:Initializing backend: sqlite /home/x/.mythtv/cache/tvdb_api3/tvdb_api
DEBUG:requests_cache.backends.base:Initializing SQLitePickleDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0x7f9b045c8dc0>
DEBUG:requests_cache.backends.sqlite:Opening connection to /home/x/.mythtv/cache/tvdb_api3/tvdb_api.sqlite:responses
DEBUG:requests_cache.backends.base:Initializing SQLiteDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0x7f9b045c8dc0>
DEBUG:requests_cache.backends.sqlite:Opening connection to /home/x/.mythtv/cache/tvdb_api3/tvdb_api.sqlite:redirects
INFO:requests_cache.backends.base:Removing expired responses.
DEBUG:requests_cache.backends.base:Deleting 0 invalid/expired responses
DEBUG:requests_cache.backends.base:Deleting 0 expired responses
DEBUG:tvdb_api:Getting show Chernobyl
DEBUG:tvdb_api:Searching for show Chernobyl
DEBUG:tvdb_api:auth
Traceback (most recent call last):
  File "/home/x/tmp/./ttvdb.py", line 2721, in <module>
    sys.exit(main())
  File "/home/x/tmp/./ttvdb.py", line 2523, in main
    seriesfound=searchseries(t, opts, series_season_ep)
  File "/home/x/tmp/./ttvdb.py", line 1537, in searchseries
    series_data = search_for_series(t, series_name, opts.language)
  File "/home/x/tmp/./ttvdb.py", line 1519, in search_for_series
    return tvdb[sid_or_name]
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdb/tvdb_api.py", line 1185, in __getitem__
    sid = self._nameToSid(key)
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdb/tvdb_api.py", line 1164, in _nameToSid
    selected_series = self._getSeries(name)
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdb/tvdb_api.py", line 933, in _getSeries
    allSeries = self.search(series)
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdb/tvdb_api.py", line 913, in search
    seriesEt = self._getetsrc(self.config['url_getSeries'] % (series))
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdb/tvdb_api.py", line 870, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdb/tvdb_api.py", line 817, in _loadUrl
    self.authorize()
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdb/tvdb_api.py", line 857, in authorize
    r = self.session.post('https://api.thetvdb.com/login', json=self.config['auth_payload'], headers=self.headers)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests_cache/session.py", line 115, in request
    return super().request(method, url, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests_cache/session.py", line 127, in send
    cache_key = self.cache.create_key(request, **kwargs)
TypeError: create_key() got an unexpected keyword argument 'timeout'
```

**Comment by rcrdnalor** [comment]
Issue closed by commit [e4ce1b.](https://github.com/MythTV/mythtv/commit/7e4ce1ba987cf8420c1c293c6bafe665a0ff3d98)
No actions for fixes/32 or master needed, because they switched to the thetvdb.com API v4 already.
