### ISSUE TITLE
mythfrontend: crash in AvFormatDecoder::GetTrackDesc(uint type, uint TrackNo) when playing specific DVD

### ISSUE THREAD

**Issue by HolgerBirkmeyer** [MythTV/mythtv#528]
* **Platform Linux nitro-lnx 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux**:

* **MythTV version fixes/32**:

* **Package version v32.0+fixes.202203050617.e78a0c0042~ubuntu20.04.1**:

* **Component mythfrontend**:

### What steps will reproduce the bug?

While most DVDs do not show an issue, with "Pirates of the Caribbean" mythfrontend crashes reliably when the main movie starts

### How often does it reproduce? Is there a required condition?

with the DVD above, it happens always

### What is the expected behavior?

Analyzing the core dump, it seems, that AvFormatDecoder::GetTrackDesc(uint type, uint TrackNo) runs into an issue:

```
    int av_index = m_tracks[type][TrackNo].m_av_stream_index;
    AVStream *stream = m_ic->streams[av_index];
    AVDictionaryEntry *entry =
        stream ? av_dict_get(stream->metadata, "title", NULL, 0) : nullptr;
```

In my case, av_index is -1 which leads to an invalid array access, leading to an invalid stream pointer. Please see gdb output below:

```
#0  0x00007f800e9b19e5 in AvFormatDecoder::GetTrackDesc (this=0x5597279be8e0, type=3, TrackNo=6) at decoders/avformatdecoder.cpp:4137
#1  0x00007f800e92ea59 in MythPlayerCaptionsUI::EnableCaptions (this=0x559727944e80, Mode=4, UpdateOSD=<optimized out>) at mythplayercaptionsui.cpp:211
#2  0x00007f800e92db83 in MythPlayerCaptionsUI::SetCaptionsEnabled (this=0x559727944e80, Enable=<optimized out>, UpdateOSD=<optimized out>) at mythplayercaptionsui.cpp:309
#3  0x00007f80094c2c2a in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f800d30ba66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007f800d3150f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007f800949680a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f8009499488 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f80094eee37 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f80039c717d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0

(gdb) p av_index
$1 = -1
(gdb) 
```

**Comment by HolgerBirkmeyer** [comment]
@linuxdude42 FYI

**Comment by HolgerBirkmeyer** [comment]
core file available on request. my irc nick is holbirkm.

**Comment by ulmus-scott** [comment]
@linuxdude42 This should protect against that invalid array access:
```
diff --git a/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp b/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
index 95a0a8d948..834b7d47c0 100644
--- a/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
+++ b/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
@@ -4133,7 +4133,11 @@ QString AvFormatDecoder::GetTrackDesc(uint type, uint TrackNo)
     QString forcedString = forced ? QObject::tr(" (forced)") : "";
 
     int av_index = m_tracks[type][TrackNo].m_av_stream_index;
-    AVStream *stream = m_ic->streams[av_index];
+    AVStream *stream = nullptr;
+    if (av_index >= 0 && av_index < m_ic->nb_streams)
+    {
+        stream = m_ic->streams[av_index];
+    }
     AVDictionaryEntry *entry =
         stream ? av_dict_get(stream->metadata, "title", NULL, 0) : nullptr;
     QString user_title = entry ? QString(R"( "%1")").arg(entry->value) : "";

```
