### ISSUE TITLE
ttvdb4.py crashes with Unicode Encode Error

### ISSUE THREAD

**Issue by tunerooster** [MythTV/mythtv#744]
* **Platform**: Linux 5.17.8-gentoo

* **MythTV version**: 33.1

* **Package version**: Compiled from source

* **Component**: ttvdb4.py

### What steps will reproduce the bug?

ttvdb4.py --debug -N 'Austin City Limits' 'Billie Eilish'

### How often does it reproduce? Is there a required condition?

Always.  No required condition.

### What is the expected behaviour?

Run to completion and report  XML.  I.e. not crash with:
```
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 68: ordinal not in range(256)
```

### What do you see instead?

```
000: Init: cmd_args:  {'version': False, 'test': False, 'language': 'en', 'country': None, 'tvtitle': None, 'tvdata': None, 'collectionref': None, 'tvnumbers': ['Austin City Limits', 'Billie Eilish'], 'inifile': 'ttvdb4.ini', 'debug': True, 'jsondebug': False, 'doctest': False}
0000: Init: Global Config File parsed successfully.
0000: Init: Local Config File '/var/lib/mythtv/.mythtv/ttvdb4.ini' parsed successfully.
0000: Init: Using this configuration:
{'AccessToken': {'Lifetime': '1'},
 'Authorization': {},
 'ConfigVersion': {'TTVDBv4ConfigVersion': '1'},
 'InetrefConversions': {},
 'Languages': {'Lang1': 'eng'},
 'Preferences': {'ShowPeople': '1'},
 'Thresholds': {'NameThreshold': '0.99',
                'ThresholdDecrease': '0.1',
                'ThresholdStart': '0.60'},
 'TitleConversions': {},
 'auth_file': '/var/lib/mythtv/.mythtv/cache/py3ttvdb4_bearer.pickle'}
0000: Init: Using this lifetime for the access token: '1' day(s).
0000: Init: Using these languages to search: 'eng'
0000: Init: Using these preferences to search:
  'ShowPeople' : 'True'
0000: Init: Using these thresholds for name searching:
  'NameThreshold' : '0.99'
  'ThresholdStart' : '0.60'
  'ThresholdDecrease' : '0.10'
0000: Init: Title and Inetref Conversions:
  Done
0000: Init: Bearer Authentication:
  Cached authentication token is valid.
  Bearer Authentication passed with 'success'.

0000: buildNumbers: Query 'buildNumbers' called with 'Austin City Limits' 'Billie Eilish'

0000: buildList: Query 'buildList' called with 'Austin City Limits', xml_output = False
0000: buildList: Found unique match for 'Austin City Limits': 71649

0000: buildList: Chosen series record according 'overall name similarity': '1.00':

0000: buildCollection: Query 'buildCollection' called with '71649', xml_output = False
0000: buildCollection: Series information for 71649:
     abbreviation  :  
     airsDays  :  <MythTV.ttvdbv4.definitions.SeriesAirsDays object at 0x7fcb6c2570d0>
     airsTime  :  None
     airsTimeUTC  :  
     aliases  :  [  ]
     artworks  :  [  69 items  ]
     averageRuntime  :  46
     characters  :  [  0 items  ]
     contentRatings  :  [  1 items  ]
     country  :  
     defaultSeasonType  :  1
     firstAired  :  1974-10-17
     genres  :  [  2 items  ]
     id  :  71649
     image  :  https://artworks.thetvdb.com/banners/posters/71649-4.jpg
     isOrderRandomized  :  False
     lastAired  :  2023-02-18
     lastUpdated  :  2023-03-01 19:48:10
     name  :  Austin City Limits
     nameTranslations  :  ['eng', 'pt']
     companies  :  [  2 items  ]
     nextAired  :  
     originalCountry  :  usa
     originalLanguage  :  eng
     originalNetwork  :  <MythTV.ttvdbv4.definitions.Company object at 0x7fcb6c256f50>
     overview  :  Established singer-songwriters and acclaimed newcomers perform country, blues, rock, folk, bluegrass, and related styles of music.
     latestNetwork  :  <MythTV.ttvdbv4.definitions.Company object at 0x7fcb6c0e1b70>
     overviewTranslations  :  [  2 items  ]
     remoteIds  :  [  3 items  ]
     score  :  332
     seasons  :  [  54 items  ]
     seasonTypes  :  [  3 items  ]
     slug  :  austin-city-limits
     status  :  <MythTV.ttvdbv4.definitions.Status object at 0x7fcb6c0e1cc0>
     tags  :  [  1 items  ]
     trailers  :  [  0 items  ]
     translations  :  [  0 items  ]
     fetched_translations  :  [ Austin City Limits ]
     name_similarity  :  1.00
0000: buildNumbers: Checking series named 'Austin City Limits' with inetref '71649':
0001: buildNumbers: Found episode names: 'Larry Gatlin / Nanci Griffith'
    with name similarity : 0.21
    with inetref 71649 : season# 10 : episode# 11 
0001: buildNumbers: Found episode names: 'Neil Young and The International Harvesters'
    with name similarity : 0.19
    with inetref 71649 : season# 10 : episode# 2 
Traceback (most recent call last):
  File "/usr/share/mythtv/metadata/Television/./ttvdb4.py", line 284, in <module>
    main()
  File "/usr/share/mythtv/metadata/Television/./ttvdb4.py", line 267, in main
    mttvdb.buildNumbers()
  File "/usr/lib/python3.10/site-packages/MythTV/ttvdbv4/myth4ttvdbv4.py", line 830, in buildNumbers
    print("%04d: buildNumbers: Found episode names: '%s'"
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 68: ordinal not in range(256)
```
### Additional information

Same thing happens on many other titles...

Using shebang #!/usr/bin/python3.10

Thanks!!!

**Comment by rcrdnalor** [comment]
Works for me:
```
0001: buildNumbers: Checking series named 'Austin City Limits' with inetref '71649':
0001: buildNumbers: Found episode names: 'Larry Gatlin / Nanci Griffith'
    with name similarity : 0.21
    with inetref 71649 : season# 10 : episode# 11 
0002: buildNumbers: Found episode names: 'Neil Young and The International Harvesters'
    with name similarity : 0.19
    with inetref 71649 : season# 10 : episode# 2 
0002: buildNumbers: Found episode names: 'Oak Ridge Boys / Bob Wills’ Original Texas Playboys'
    with name similarity : 0.16
    with inetref 71649 : season# 10 : episode# 1 
```
Note: The single backtick in "Bob Wills’ Original Texas Playboys" is not an ascii character.
Maybe a locale issue:
Please post the output of the command in terminal
```
locale
```

**Comment by tunerooster** [comment]
I ran locale:
```
LANG=en_US.iso88591
LC_CTYPE="en_US.iso88591"
LC_NUMERIC="en_US.iso88591"
LC_TIME="en_US.iso88591"
LC_COLLATE="en_US.iso88591"
LC_MONETARY="en_US.iso88591"
LC_MESSAGES="en_US.iso88591"
LC_PAPER="en_US.iso88591"
LC_NAME="en_US.iso88591"
LC_ADDRESS="en_US.iso88591"
LC_TELEPHONE="en_US.iso88591"
LC_MEASUREMENT="en_US.iso88591"
LC_IDENTIFICATION="en_US.iso88591"
LC_ALL=
```
I changed it to:
```
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```
It now seems to be working!!! (at least on the ones I have re-tested so far)...  I expect it will now work on all the similar failures.  BIG THANKS for the tip!   _Maybe a note in the requirements section is warranted._

I am closing the issue...    :+1:
